### ISSUE TITLE
Partial support

### ISSUE THREAD

**Issue by TheHunterDog** [trapcodeio/vite-plugin-ejs#6]
There is no support for Partials

**Comment by trapcodeio** [comment]
There is partial support but it is not documented or supported by default.
You have to set the `views` configuration for `ejs` like so.

```js
export default defineConfig({
  plugins: [ 
    ViteEjsPlugin(
      {title: 'My vue project!'},
      {
        ejs: {
          // set views path to support partials
          views: [__dirname],
        },
      }
    ),
  ],
});
```

I will publish an update to support partials by default in the next few days since it does not affect performance.
For now use this and let me know if it served you.

A demo can be found here on stackblitz: [vite-plugin-ejs-test](https://stackblitz.com/edit/vite-plugin-ejs?file=index.html)

**Comment by trapcodeio** [comment]
If you update to `1.6.2` you should have partial support.

Update: [https://github.com/trapcodeio/vite-plugin-ejs/releases/tag/v1.6.2](https://github.com/trapcodeio/vite-plugin-ejs/releases/tag/v1.6.2)
